[package]
name = "parcel_selectors"
version = "0.26.4"
authors = ["The Servo Project Developers"]
documentation = "https://docs.rs/parcel_selectors/"
description = "CSS Selectors matching for Rust - forked for lightningcss"
repository = "https://github.com/parcel-bundler/lightningcss"
readme = "README.md"
keywords = ["css", "selectors"]
license = "MPL-2.0"
build = "build.rs"

[lib]
name = "parcel_selectors"
path = "lib.rs"

[features]
bench = []
jsonschema = ["serde", "schemars"]
into_owned = ["static-self"]
smallvec = ["static-self/smallvec"]
serde = ["dep:serde", "smallvec/serde"]

[dependencies]
bitflags = "2.2.1"
cssparser = {path = "../rust-cssparser"}
fxhash = "0.2"
log = "0.4"
phf = "0.10"
precomputed-hash = "0.1"
smallvec = "1.0"
serde = { version = "1.0.123", features = ["derive"], optional = true }
schemars = { version = "0.8.11", features = ["smallvec"], optional = true }
static-self = { version = "0.1.0", path = "../static-self", optional = true }

[build-dependencies]
phf_codegen = "0.10"
